spring:
  datasource:
    driver: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//192.168.1.248:1521/orcl
    username: tms_test
    password: oracle
    ddl-auto: update
    initial-size: 5
  props:
    sql:
      show: true
mybatis:
  properties: db_alias_ops :ops_db,db_alias_oms :oms_db,db_alias_lmdm :lmdm_db,db_alias_tms :tms_db



